openapi: 3.2.0
info:
  description: TileDB Storage Platform REST API
  title: TileDB Storage Platform Assets API
  version: 2.17.51
servers:
- url: /v1
security:
- BasicAuth: []
- ApiKeyAuth: []
tags:
- name: Assets
paths:
  /assets/{namespace}:
    parameters:
    - name: namespace
      in: path
      description: namespace
      required: true
      schema:
        type: string
    - name: asset_type
      in: query
      description: asset_type to filter to
      required: false
      schema:
        type: string
    - name: ownership_level
      in: query
      description: ownership_level to filter to (owned, shared)
      required: false
      schema:
        type: string
    - name: depth
      in: query
      description: depth of assets to be returned
      required: false
      schema:
        type: string
    - name: search
      in: query
      description: search string
      required: false
      schema:
        type: string
    - name: page
      in: query
      description: pagination offset
      required: false
      schema:
        type: integer
    - name: per_page
      in: query
      description: pagination limit
      required: false
      schema:
        type: integer
    - name: order_by
      in: query
      description: 'order by a specific property, defaults to `created_at desc`

        supported values are created_at, name, asset_type

        can also include the order type (asc or desc) separated by space

        i.e. `name asc` `name desc` etc.

        '
      required: false
      schema:
        type: string
    - name: expand
      in: query
      description: expansion option for the AssetInfo object to be added to the response
      required: false
      schema:
        type: string
    get:
      tags:
      - Assets
      description: List assets in a namespace
      operationId: listAssets
      responses:
        200:
          description: Successful list of assets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetListResponse'
        502:
          description: Bad Gateway
        default:
          description: error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      summary: List assets
      x-summary-source: derived
  /public_assets:
    parameters:
    - name: asset_type
      in: query
      description: asset_type to filter to
      required: false
      schema:
        type: string
    - name: depth
      in: query
      description: depth of assets to be returned
      required: false
      schema:
        type: string
    - name: search
      in: query
      description: search string
      required: false
      schema:
        type: string
    - name: page
      in: query
      description: pagination offset
      required: false
      schema:
        type: integer
    - name: per_page
      in: query
      description: pagination limit
      required: false
      schema:
        type: integer
    - name: order_by
      in: query
      description: 'order by a specific property, defaults to `created_at desc`

        supported values are created_at, name, asset_type

        can also include the order type (asc or desc) separated by space

        i.e. `name asc` `name desc` etc.

        '
      required: false
      schema:
        type: string
    get:
      tags:
      - Assets
      operationId: listPublicAssets
      responses:
        200:
          description: Successful list of assets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetListResponse'
        502:
          description: Bad Gateway
        default:
          description: error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      summary: List public assets
      x-summary-source: derived
  /assets/{namespace}/change_credentials:
    parameters:
    - name: namespace
      in: path
      description: The namespace to send the request on behalf of.
      required: true
      schema:
        type: string
    post:
      tags:
      - Assets
      description: Changes the access credentials to the given assets
      operationId: changeAssetCredentials
      responses:
        204:
          description: Credentials changed successfully
        502:
          description: Bad Gateway
        default:
          description: error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeAssetCredentialsRequest'
        description: aws access credentials to store for a namespace
        required: true
      summary: Change asset credentials
      x-summary-source: derived
components:
  schemas:
    MetadataStringifiedEntry:
      type: object
      description: key/value pair representing an asset metadata map entry
      properties:
        key:
          description: The metadata key
          type: string
          x-omitempty: false
        value:
          description: The metadata value
          type: string
          x-omitempty: false
        type:
          description: The metadata type
          type: string
          x-omitempty: false
          example: array_metadata
    ChangeAssetCredentialsRequest:
      description: Request body to change the credentials of the given assets
      type: object
      required:
      - access_credentials
      - asset_uuids
      properties:
        access_credentials:
          description: The name or uuid of the access credentials
          type: string
        asset_uuids:
          description: The list of asset uuids to have their credentials changed
          type: array
          items:
            type: string
    PaginationMetadata:
      properties:
        page:
          description: pagination offset. Use it to skip the first ((page - 1) * per_page) items
          type: number
          format: uint64
          example: 1
        per_page:
          description: pagination limit (page size)
          type: number
          format: uint64
          example: 10
        total_pages:
          description: number of total pages with current limit
          type: number
          format: uint64
          example: 14
        total_items:
          description: number of total available items
          type: number
          format: uint64
          example: 138
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
        request_id:
          type: string
    AssetBackingType:
      description: The technology that an asset is backed by
      type: string
      enum:
      - array
      - group
    MetadataStringified:
      type: object
      description: The user's TileDB metadata
      properties:
        entries:
          description: List of metadata entries
          type: array
          x-omitempty: true
          items:
            $ref: '#/components/schemas/MetadataStringifiedEntry'
    AssetInfo:
      description: metadata of an asset
      type: object
      properties:
        uuid:
          description: unique ID of a registered asset
          type: string
          example: 00000000-0000-0000-0000-000000000000
        asset_type:
          description: Asset type of an asset
          $ref: '#/components/schemas/AssetType'
        asset_backing_type:
          description: Asset type of an asset
          $ref: '#/components/schemas/AssetBackingType'
        asset_ownership_level:
          description: Ownership level of the asset
          $ref: '#/components/schemas/AssetOwnershipLevel'
        namespace_name:
          description: namespace_name that the asset is registered to
          type: string
          example: user1
        namespace_uuid:
          description: namespace_uuid that the asset is registered to
          type: string
          example: 00000000-0000-0000-0000-000000000000
        name:
          description: name of asset
          type: string
          example: myarray1
        mime_type:
          description: mime type of the asset
          type: string
          example: application/vnd.tiledb.v1.array
        created_at:
          description: Time when the asset was created (rfc3339)
          type: string
          format: date-time
          readOnly: true
        metadata:
          description: metadata for the asset, only included when expanded
          $ref: '#/components/schemas/MetadataStringified'
    AssetType:
      description: Asset types represented as TileDB arrays
      type: string
      enum:
      - array
      - notebook
      - dashboard
      - user_defined_function
      - ml_model
      - file
      - registered_task_graph
      - group
      - vcf
      - soma
      - pointcloud
      - bioimg
      - geometry
      - raster
      - vector_search
    AssetListResponse:
      description: Asset associated with a TileDB Cloud account
      type: object
      properties:
        data:
          description: asset information for each asset
          type: array
          x-omitempty: true
          items:
            $ref: '#/components/schemas/AssetInfo'
        pagination_metadata:
          $ref: '#/components/schemas/PaginationMetadata'
    AssetOwnershipLevel:
      description: The ownership level of the asset
      type: string
      enum:
      - owned
      - shared
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-TILEDB-REST-API-KEY
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants read and write access to administrative information
          authorizationUrl: https://oauth2.tiledb.com/oauth2/authorize
          tokenUrl: https://oauth2.tiledb.com/oauth2/token
