openapi: 3.2.0
info:
  description: TileDB Storage Platform REST API
  title: TileDB Storage Platform Array Tasks API
  version: 2.17.51
servers:
- url: /v1
security:
- BasicAuth: []
- ApiKeyAuth: []
tags:
- name: array_tasks
paths:
  /tasks/sidebar:
    parameters:
    - name: start
      in: query
      description: Fetch tasks created after this time, unix epoch in seconds, default 7 days ago
      schema:
        type: integer
        format: uint64
    - name: end
      in: query
      description: Fetch tasks created before this time, unix epoch in seconds, default now
      schema:
        type: integer
        format: uint64
    get:
      tags:
      - array_tasks
      operationId: getArrayTasksSidebar
      responses:
        200:
          description: sidebar metadata for task definitions for all arrays user has access to
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayTaskBrowserSidebar'
              example:
                organizations:
                - organization1
                - organization2
                - organization3
                result_count_for_all: 74
                result_count_by_namespace:
                  mockuser: 14
                  organization1: 6
                  organization2: 52
                  organization3: 2
        404:
          description: array tasks not found
        502:
          description: Bad Gateway
        default:
          description: error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: Error try again
                code: 1
      summary: Get array tasks sidebar
      x-summary-source: derived
components:
  schemas:
    ArrayTaskBrowserSidebar:
      description: Object for ui array tasks browser page
      type: object
      properties:
        organizations:
          description: list of all unique organizations the user is part of that have array tasks
          type: array
          x-omitempty: false
          items:
            type: string
        result_count_for_all:
          description: A count of "all"
          x-omitempty: false
          type: integer
        result_count_by_namespace:
          description: A map that includes the result count by namespace
          x-omitempty: false
          additionalProperties:
            type: integer
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
        request_id:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-TILEDB-REST-API-KEY
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants read and write access to administrative information
          authorizationUrl: https://oauth2.tiledb.com/oauth2/authorize
          tokenUrl: https://oauth2.tiledb.com/oauth2/token
